FROM ubuntu:18.04

# Get packages
RUN apt-get update && apt-get install -y \
	fluxbox \
	x11vnc  \
	xserver-xorg-video-dummy \
	x11-xserver-utils \
	supervisor

# Set environment variables to default values
ENV DISPLAY=:0 \
	PASSWORD="" \
	HOME=/root

WORKDIR $HOME

# Install noVNC	and websockify, and create required links
ADD ./xserver/novnc/noVNC-1.1.0.tar.gz $HOME
ADD ./xserver/novnc/websockify-0.9.0.tar.gz $HOME

RUN ln -s $HOME/noVNC-1.1.0 $HOME/noVNC && \
	ln -s $HOME/websockify-0.9.0 $HOME/noVNC/utils/websockify

# Prepare supervisor log
RUN mkdir -p /var/log/supervisor

# Install configuration for supervisor
COPY ./xserver/supervisor-xdummy $HOME

# Install configuration for fluxbox
COPY ./xserver/fluxbox $HOME/.fluxbox/

# Add xdummy configuration
ADD ./xserver/xdummy/xorg.conf /etc/X11/xorg.conf

# Expose VNC, SUPERVISOR, and Websocker port 
EXPOSE 5900 9001 8080

# Set entrypoint
CMD ["/usr/bin/supervisord", "-c", "supervisord.conf"]
